//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karmolin_Fitness_Center_.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRecords
    {
        public int IdVisit { get; set; }
        public int IdCard { get; set; }
        public int IdTrainer { get; set; }
        public System.DateTime VisitData { get; set; }
        public System.TimeSpan VisitTime { get; set; }
    
        public virtual ListOfTrainers ListOfTrainers { get; set; }
        public virtual SaleSubscription SaleSubscription { get; set; }
    }
}
