//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karmolin_Fitness_Center_.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfTrainers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListOfTrainers()
        {
            this.AttendanceRecords = new HashSet<AttendanceRecords>();
        }
    
        public int IdTrainer { get; set; }
        public string IdUser { get; set; }
        public int IdSpecialization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceRecords> AttendanceRecords { get; set; }
        public virtual TrainerSpecialization TrainerSpecialization { get; set; }
    }
}
