//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karmolin_Fitness_Center_.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerSpecialization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainerSpecialization()
        {
            this.ListOfTrainers = new HashSet<ListOfTrainers>();
        }
    
        public int IdSpecialization { get; set; }
        public string NameSpecialization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOfTrainers> ListOfTrainers { get; set; }
    }
}
